"use client";

import { createAlarmPlan, formatInstant } from "@prophetic-night/night-engine";
import type {
  AlarmPreferences,
  NightCalculationInput,
  NightCalculationResult,
} from "@prophetic-night/night-engine";
import { useMemo, useState } from "react";

interface ScheduleToolsProps {
  result: NightCalculationResult;
  input: NightCalculationInput;
}

function calendarInstant(value: string): string {
  return new Date(value)
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}/, "");
}

function calendarText(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

function downloadCalendar(result: NightCalculationResult, preferences: AlarmPreferences) {
  const events = createAlarmPlan(result, preferences)
    .alarms.map((alarm) => {
      const end = new Date(Date.parse(alarm.instant) + 5 * 60_000).toISOString();
      return [
        "BEGIN:VEVENT",
        `UID:${alarm.id}-${Date.parse(alarm.instant)}@prophetic-night-segments`,
        `DTSTAMP:${calendarInstant(result.night.start)}`,
        `DTSTART:${calendarInstant(alarm.instant)}`,
        `DTEND:${calendarInstant(end)}`,
        `SUMMARY:${calendarText(alarm.label)}`,
        `DESCRIPTION:${calendarText("Informational scheduling reminder generated by Prophetic Night Segments.")}`,
        "END:VEVENT",
      ].join("\r\n");
    })
    .join("\r\n");
  const contents = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Prophetic Night Segments//EN",
    events,
    "END:VCALENDAR",
  ].join("\r\n");
  const url = URL.createObjectURL(new Blob([contents], { type: "text/calendar;charset=utf-8" }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "prophetic-night-segments-alarms.ics";
  anchor.click();
  URL.revokeObjectURL(url);
}

export function ScheduleTools({ result, input }: ScheduleToolsProps) {
  const [preferences, setPreferences] = useState<AlarmPreferences>({
    atPart4: true,
    atLastThird: true,
    endPrayerAtPart6: true,
    fajrPreparationMinutes: 20,
  });
  const plan = useMemo(() => createAlarmPlan(result, preferences), [result, preferences]);

  function updateCustomMinutes(value: string) {
    const next = { ...preferences };
    if (value === "") delete next.minutesBeforeFajr;
    else next.minutesBeforeFajr = Number(value);
    setPreferences(next);
  }

  return (
    <section
      className="border border-white/10 bg-[#0c2229] p-5 sm:p-9"
      aria-labelledby="alarms-title"
    >
      <p className="text-xs font-bold tracking-[0.18em] text-[#d0ae67]">03 / PLAN</p>
      <h2 id="alarms-title" className="mt-3 font-serif text-3xl">
        Alarm planning
      </h2>
      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        {(
          [
            ["atPart4", "Wake at beginning of Part 4"],
            ["atPart5", "Wake at beginning of Part 5"],
            ["atLastThird", "Wake at beginning of last third"],
            ["endPrayerAtPart6", "End prayer at beginning of Part 6"],
          ] as const
        ).map(([key, label]) => (
          <label key={key} className="flex items-center gap-3 border border-white/10 p-3">
            <input
              type="checkbox"
              checked={Boolean(preferences[key])}
              onChange={(event) => setPreferences({ ...preferences, [key]: event.target.checked })}
            />
            {label}
          </label>
        ))}
        <label className="grid gap-2 text-sm text-[#c8d4d0]">
          Custom minutes before Fajr
          <input
            type="number"
            min="0"
            value={preferences.minutesBeforeFajr ?? ""}
            onChange={(event) => updateCustomMinutes(event.target.value)}
            className="border border-white/20 bg-[#06151a] px-3 py-2 text-white"
          />
        </label>
      </div>
      <div className="mt-6 divide-y divide-white/10 border-y border-white/10" aria-live="polite">
        {plan.alarms.map((alarm) => (
          <p key={alarm.id} className="flex flex-wrap justify-between gap-3 py-3">
            <span>{alarm.label}</span>
            <strong className="text-[#d0ae67]">
              {formatInstant(alarm.instant, {
                timeZone: input.timeZone,
                displayFormat: "24h",
              })}
            </strong>
          </p>
        ))}
      </div>
      <button
        type="button"
        onClick={() => downloadCalendar(result, preferences)}
        className="mt-6 border border-[#d0ae67] px-5 py-3 font-semibold text-[#d0ae67] hover:bg-[#d0ae67]/10"
      >
        Download calendar (.ics)
      </button>
      <p className="mt-3 text-xs leading-5 text-[#8ea29d]">
        Calendar reminders depend on your device and calendar app. A browser cannot reliably sound
        an alarm after it closes.
      </p>
    </section>
  );
}
