"use client";

import { createAlarmPlan, formatInstant } from "@prophetic-night/night-engine";
import type { AlarmPreferences, NightCalculationResult } from "@prophetic-night/night-engine";
import { useMemo } from "react";
import { generateICS } from "@/lib/calendar/generateICS";

interface NightEndEvent {
  id: "buffer-wake-up" | "first-adhan-reminder" | "buffer-before-fajr" | "fajr";
  label: string;
  instant: string;
}

export const DEFAULT_BUFFER_BEFORE_FAJR_MINUTES = 20;

export function createNightEndSchedule(
  result: NightCalculationResult,
  fajrPreparationMinutes: number,
  firstAdhanMinutes: number | null,
): NightEndEvent[] {
  const fajr = Date.parse(result.night.end);
  const events: NightEndEvent[] = [
    {
      id: "buffer-wake-up",
      label: "Buffer Wake-Up Time",
      instant: result.dawudPattern.fajrWake.suggestedAlarm,
    },
    {
      id: "buffer-before-fajr",
      label: "Buffer Before Fajr",
      instant: new Date(fajr - fajrPreparationMinutes * 60_000).toISOString(),
    },
    { id: "fajr", label: "Fajr", instant: result.night.end },
  ];
  if (firstAdhanMinutes !== null) {
    events.push({
      id: "first-adhan-reminder",
      label: "Wake before Fajr",
      instant: new Date(fajr - firstAdhanMinutes * 60_000).toISOString(),
    });
  }
  return events.sort((left, right) => Date.parse(left.instant) - Date.parse(right.instant));
}

interface NightEndTimelineProps {
  result: NightCalculationResult;
  timeZone: string;
  firstAdhanMinutes: number | null;
  bufferBeforeFajrMinutes?: number;
}

export function NightEndTimeline({
  result,
  timeZone,
  firstAdhanMinutes,
  bufferBeforeFajrMinutes = DEFAULT_BUFFER_BEFORE_FAJR_MINUTES,
}: NightEndTimelineProps) {
  const schedule = useMemo(
    () => createNightEndSchedule(result, bufferBeforeFajrMinutes, firstAdhanMinutes),
    [result, bufferBeforeFajrMinutes, firstAdhanMinutes],
  );

  return (
    <section
      className="mt-7 border border-white/10 bg-[#0c2229] p-5 sm:p-7"
      aria-labelledby="night-end-title"
    >
      <p className="text-xs font-bold tracking-[0.16em] text-[#d0ae67]">END OF NIGHT</p>
      <h3 id="night-end-title" className="mt-2 font-serif text-2xl">
        End of the calculated night
      </h3>
      <p className="mt-2 text-sm leading-6 text-[#9baca7]">
        Events are shown in chronological order. Fajr remains the final boundary of the Islamic
        night.
      </p>
      <ol className="mt-5 grid gap-2" aria-live="polite">
        {schedule.map((event, index) => {
          const coincidesWithPrevious = index > 0 && schedule[index - 1]!.instant === event.instant;
          return (
            <li
              key={event.id}
              className={`grid grid-cols-[1.25rem_1fr_auto] items-center gap-3 border p-3 ${
                event.id === "fajr"
                  ? "border-[#d0ae67] bg-[#d0ae67]/10"
                  : "border-white/10 bg-[#06151a]"
              }`}
            >
              <span aria-hidden="true" className="text-center text-[#d0ae67]">
                {index === schedule.length - 1 ? "●" : "↓"}
              </span>
              <span>
                {event.label}
                {coincidesWithPrevious && (
                  <span className="ml-2 text-xs text-[#8ea29d]">Same time as above</span>
                )}
              </span>
              <strong className="text-[#d0ae67]">
                {formatInstant(event.instant, { timeZone, displayFormat: "24h" })}
              </strong>
            </li>
          );
        })}
      </ol>
      <p className="mt-3 text-xs leading-5 text-[#8ea29d]">
        Fajr is the beginning of Fajr / true dawn (al-Fajr al-Ṣādiq). Wake before Fajr is a selected
        scheduling offset, not an astronomical dawn calculation.
      </p>
    </section>
  );
}

export function createCalendarContents(
  result: NightCalculationResult,
  preferences: AlarmPreferences,
  firstAdhanMinutes: number | null,
): string {
  const alarms = createAlarmPlan(result, preferences).alarms;
  if (firstAdhanMinutes !== null) {
    alarms.push({
      id: "first-adhan-reminder",
      label: "Wake before Fajr",
      instant: new Date(Date.parse(result.night.end) - firstAdhanMinutes * 60_000).toISOString(),
    });
  }
  return generateICS(
    alarms.map((alarm) => ({
      id: alarm.id,
      title: alarm.label,
      start: alarm.instant,
      end: new Date(Date.parse(alarm.instant) + 5 * 60_000).toISOString(),
      description: "Informational scheduling reminder generated by Prophetic Night Segments.",
      timeZone: result.input.timeZone,
    })),
    result.night.start,
  );
}
