import { createAlarmPlan, type NightCalculationResult } from "@prophetic-night/night-engine";
import {
  buildCalendarEvents,
  NIGHT_PART_TITLES,
  type CalendarEvent,
  buildDailyPrayerEvents,
  type DailyPrayerSchedule,
} from "@/lib/calendar/buildCalendarEvents";

export const GOOGLE_EVENT_TITLES = {
  ...NIGHT_PART_TITLES,
  wake: "Qiyam / Tahajjud — Wake Up",
  "last-third": "Qiyam / Tahajjud — Last Third Begins",
  "part-4": "Qiyam / Tahajjud — Beginning of Part 4",
  "part-5": "Qiyam / Tahajjud — Beginning of Part 5",
  "dawud-prayer": "Dāwūd Pattern — Prayer Window",
  "part-6": "Qiyam / Tahajjud — Go Back to Sleep",
  "fajr-preparation": "Prepare for Fajr",
  "first-adhan-reminder": "Wake before Fajr",
  fajr: "Fajr",
  "final-sixth": "Sixth of the Night — Final Sixth",
  prayer: "Qiyam / Tahajjud — Prayer Window",
  "prayer-fajr": "Fajr",
  "prayer-dhuhr": "Dhuhr",
  "prayer-asr": "Asr",
  "prayer-maghrib": "Maghrib",
  "prayer-isha": "Isha",
  "fasting-monday": "Fasting — Monday",
  "fasting-thursday": "Fasting — Thursday",
  "fasting-white-day": "Fasting — White Day",
  "fasting-dawud": "Fasting — Dāwūd schedule",
} as const;
export type GoogleEventId = keyof typeof GOOGLE_EVENT_TITLES;
const DAWUD_CONTEXT =
  "The Dāwūd schedule is based on the authentic narration describing half the night sleeping, one third praying, and the final sixth sleeping (Ṣaḥīḥ al-Bukhārī 1131). Parts 4–5 are distinct from the mathematical last third. This does not imply that Prophet Muhammad ﷺ followed a fixed six-part schedule.";

export function buildGooglePlan(
  result: NightCalculationResult,
  options: {
    wakeBufferMinutes: number;
    dawudSelected: boolean;
    prayerSource: string;
    fajrPreparationMinutes: number;
    firstAdhanMinutes: number | null;
    dailyPrayerSchedule?: DailyPrayerSchedule;
  },
): CalendarEvent[] {
  const base = buildCalendarEvents(result, {
    ...options,
    pattern: options.dawudSelected ? "dawud" : "last-third",
  });
  const context = `${base[0]!.description}\nGenerated by Sixth of the Night as an optional scheduling/planning aid; not a religious obligation.`;
  const make = (id: GoogleEventId, start: string, end = start, dawud = false): CalendarEvent => ({
    id,
    serviceDate: base[0]!.serviceDate,
    title: GOOGLE_EVENT_TITLES[id],
    start,
    end,
    timeZone: result.input.timeZone,
    description: `${context}${dawud ? `\n${DAWUD_CONTEXT}` : ""}`,
  });
  const alarms = createAlarmPlan(result, {
    atPart4: true,
    atPart5: true,
    endPrayerAtPart6: true,
    fajrPreparationMinutes: options.fajrPreparationMinutes,
    ...(options.firstAdhanMinutes !== null ? { minutesBeforeFajr: options.firstAdhanMinutes } : {}),
  }).alarms;
  return [
    make("wake", base[0]!.start, base[0]!.end, options.dawudSelected),
    make("last-third", result.lastThird.start),
    ...base.filter((event) => Object.hasOwn(NIGHT_PART_TITLES, event.id)),
    make("final-sixth", result.dawudPattern.finalSleep.start),
    make(
      "prayer",
      options.dawudSelected ? result.dawudPattern.prayer.start : result.lastThird.start,
      options.dawudSelected ? result.dawudPattern.prayer.end : result.lastThird.end,
      options.dawudSelected,
    ),
    make("dawud-prayer", result.dawudPattern.prayer.start, result.dawudPattern.prayer.end, true),
    ...alarms
      .filter((alarm) => alarm.id !== "part-6")
      .map((alarm) =>
        make(
          alarm.id === "custom-before-fajr" ? "first-adhan-reminder" : (alarm.id as GoogleEventId),
          alarm.instant,
          alarm.instant,
          alarm.id === "part-4" || alarm.id === "part-6",
        ),
      ),
    make("fajr", result.night.end),
    make(
      "part-6",
      result.dawudPattern.finalSleep.start,
      result.dawudPattern.finalSleep.start,
      true,
    ),
    ...(options.dailyPrayerSchedule ? buildDailyPrayerEvents(options.dailyPrayerSchedule) : []),
  ];
}
