import { createAlarmPlan, type NightCalculationResult } from "@prophetic-night/night-engine";
import { buildCalendarEvents, type CalendarEvent } from "@/lib/calendar/buildCalendarEvents";

export const GOOGLE_EVENT_TITLES = {
  wake: "Qiyam — Wake for Prayer",
  "last-third": "Qiyam — Last Third Begins",
  "part-4": "Qiyam — Beginning of Part 4",
  "part-5": "Qiyam — Beginning of Part 5",
  "dawud-prayer": "Dāwūd Pattern — Prayer Window",
  "part-6": "Qiyam — End Prayer / Beginning of Part 6",
  "fajr-preparation": "Prepare for Fajr",
  "first-adhan-reminder": "First Adhan Reminder",
  fajr: "Fajr",
  "final-sixth": "Sixth of the Night — Final Sixth",
  prayer: "Qiyam — Prayer Window",
} as const;
export type GoogleEventId = keyof typeof GOOGLE_EVENT_TITLES;
const DAWUD_CONTEXT =
  "The Dāwūd schedule is based on the authentic narration describing half the night sleeping, one third praying, and the final sixth sleeping (Ṣaḥīḥ al-Bukhārī 1131). Parts 4–5 are distinct from the mathematical last third. This does not imply that Prophet Muhammad ﷺ followed a fixed six-part schedule.";

export function buildGooglePlan(
  result: NightCalculationResult,
  options: {
    wakeBufferMinutes: number;
    dawudSelected: boolean;
    prayerSource: string;
    fajrPreparationMinutes: number;
    firstAdhanMinutes: number | null;
  },
): CalendarEvent[] {
  const base = buildCalendarEvents(result, {
    ...options,
    pattern: options.dawudSelected ? "dawud" : "last-third",
  });
  const context = `${base[0]!.description}\nGenerated by Sixth of the Night as an optional scheduling/planning aid; not a religious obligation.`;
  const make = (id: GoogleEventId, start: string, end = start, dawud = false): CalendarEvent => ({
    id,
    title: GOOGLE_EVENT_TITLES[id],
    start,
    end,
    timeZone: result.input.timeZone,
    description: `${context}${dawud ? `\n${DAWUD_CONTEXT}` : ""}`,
  });
  const alarms = createAlarmPlan(result, {
    atPart4: true,
    atPart5: true,
    endPrayerAtPart6: true,
    fajrPreparationMinutes: options.fajrPreparationMinutes,
    ...(options.firstAdhanMinutes !== null ? { minutesBeforeFajr: options.firstAdhanMinutes } : {}),
  }).alarms;
  return [
    make("wake", base[0]!.start, base[0]!.end, options.dawudSelected),
    make("last-third", result.lastThird.start),
    ...alarms.map((alarm) =>
      make(
        alarm.id === "custom-before-fajr" ? "first-adhan-reminder" : (alarm.id as GoogleEventId),
        alarm.instant,
        alarm.instant,
        alarm.id === "part-4" || alarm.id === "part-6",
      ),
    ),
    make("dawud-prayer", result.dawudPattern.prayer.start, result.dawudPattern.prayer.end, true),
    make("fajr", result.night.end),
    make("final-sixth", result.dawudPattern.finalSleep.start),
    make(
      "prayer",
      options.dawudSelected ? result.dawudPattern.prayer.start : result.lastThird.start,
      options.dawudSelected ? result.dawudPattern.prayer.end : result.lastThird.end,
      options.dawudSelected,
    ),
  ];
}
